# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Total.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.uic import loadUi
from PyQt5.QtGui import *
import sys
from PyQt5.QtCore import QObject, QThread, pyqtSignal
from MainWindow import *
from Residents import *
import time




class okaResidentt:
    def __init__(self, name, room, x_home, x_bathroom):  # room = 1;2;3;4  --  Each number represents a part of the appartment, meaning in wich part
        self.name = name                                                     # of the appartment the room is located, so which bathroom is the prefered one
        self.room = room
        self.x_home = "t"
        self.x_bathroom = "f"


# ----- these are True/False Statements whether the bathrooms are occupied or not (t = true = occupied, f= false = not occupied -----
bathBigVF = "f"
bathSmallVF = "f"
bathTopVF = "f"
label_ind = "1"
Casa_Count = 11    # This is the number of residents currently at home


class Ui_Total(object):

    # ----- The 3 play methods -----
    # ----- They simply return a random value between 1 and 200, and every possible outcome has a certain ranges of values, -----
    # ----- giving a probability of this outcome, the returned outcomes are used by the Worker Threads to then emit signals based on the outcome
    # ----- The only difference between the 3 play methods is the probability of entering each bathroom, based again on the location of the room in the h
    def play2(self, okaResidentt):
        while okaResidentt.x_home == "t" and okaResidentt.x_bathroom == "f":
            k = random.randrange(0, 200)
            if k < 11:
                return "HomeOut"
            elif 10 < k < 21:
                return "HomeIn"
            elif 20 < k < 80:
                return "BathBigOut"
            elif 79 < k < 99:
                return "BathBigIn"
            elif 98 < k < 120:
                return "BathSmallOut"
            elif 119 < k < 129:
                return "BathSmallIn"
            elif 128 < k < 160:
                return "BathTopOut"
            elif 159 < k < 165:
                return "BathTopIn"
            elif k > 164:
                return "else"

    def play3(self, okaResidentt):
        while okaResidentt.x_home == "t" and okaResidentt.x_bathroom == "f":
            k = random.randrange(0, 200)
            if k < 11:
                return "HomeOut"
            elif 10 < k < 21:
                return "HomeIn"
            elif 20 < k < 42:
                return "BathBigOut"
            elif 41 < k < 53:
                return "BathBigIn"
            elif 52 < k < 100:
                return "BathSmallOut"
            elif 99 < k < 150:
                return "BathSmallIn"
            elif 149 < k < 157:
                return "BathTopOut"
            elif 156 < k < 165:
                return "BathTopIn"
            elif k > 164:
                return "else"

    def play4(self, okaResidentt):
        while okaResidentt.x_home == "t" and okaResidentt.x_bathroom == "f":
            k = random.randrange(0, 200)
            if k < 11:
                return "HomeOut"
            elif 10 < k < 21:
                return "HomeIn"
            elif 20 < k < 42:
                return "BathBigOut"
            elif 41 < k < 53:
                return "BathBigIn"
            elif 52 < k < 65:
                return "BathSmallOut"
            elif 64 < k < 75:
                return "BathSmallIn"
            elif 74 < k < 120:
                return "BathTopOut"
            elif 119 < k < 165:
                return "BathTopIn"
            elif k > 164:
                return "else"

    # Open The Residents Window
    def openResidentss(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()

    # Click on the Start Button
    # all the worker threads are started and all the signals from the threads are connected
    def clickedStartBtn(self):
        self.label_ind = "1"
        self.labelRunningT.show()
        self.workerLabel = WorkerLabel()
        self.workerLabel.start()
        time.sleep(0.1)
        self.worker = Worker()
        self.worker.start()
        time.sleep(0.5)
        self.worker2 = Worker2()
        self.worker2.start()
        time.sleep(0.25)
        self.worker3 = Worker3()
        self.worker3.start()
        time.sleep(0.2)
        self.worker4 = Worker4()
        self.worker4.start()
        time.sleep(0.39)
        self.worker5 = Worker5()
        self.worker5.start()
        time.sleep(0.33)
        self.worker6 = Worker6()
        self.worker6.start()
        time.sleep(0.72)
        self.worker7 = Worker7()
        self.worker7.start()
        time.sleep(0.17)
        self.worker8 = Worker8()
        self.worker8.start()
        time.sleep(0.41)
        self.worker9 = Worker9()
        self.worker9.start()
        time.sleep(0.22)
        self.worker10 = Worker10()
        self.worker10.start()
        time.sleep(0.39)
        self.worker11 = Worker11()
        self.worker11.start()

        self.worker.signalMatheus1_1.connect(self.signalMatheus1_1exec)
        self.worker.signalMatheus1_2.connect(self.signalMatheus1_2exec)
        self.worker.signalMatheus2_1.connect(self.signalMatheus2_1exec)
        self.worker.signalMatheus2_2.connect(self.signalMatheus2_2exec)
        self.worker.signalMatheus3_1.connect(self.signalMatheus3_1exec)
        self.worker.signalMatheus3_2.connect(self.signalMatheus3_2exec)
        self.worker.signalMatheus4_1.connect(self.signalMatheus4_1exec)
        self.worker.signalMatheus4_2.connect(self.signalMatheus4_2exec)
        self.worker2.signalLuan1_1.connect(self.signalLuan1_1exec)
        self.worker2.signalLuan1_2.connect(self.signalLuan1_2exec)
        self.worker2.signalLuan2_1.connect(self.signalLuan2_1exec)
        self.worker2.signalLuan2_2.connect(self.signalLuan2_2exec)
        self.worker2.signalLuan3_1.connect(self.signalLuan3_1exec)
        self.worker2.signalLuan3_2.connect(self.signalLuan3_2exec)
        self.worker2.signalLuan4_1.connect(self.signalLuan4_1exec)
        self.worker2.signalLuan4_2.connect(self.signalLuan4_2exec)
        self.worker3.signalIzabella1_1.connect(self.signalIzabella1_1exec)
        self.worker3.signalIzabella1_2.connect(self.signalIzabella1_2exec)
        self.worker3.signalIzabella2_1.connect(self.signalIzabella2_1exec)
        self.worker3.signalIzabella2_2.connect(self.signalIzabella2_2exec)
        self.worker3.signalIzabella3_1.connect(self.signalIzabella3_1exec)
        self.worker3.signalIzabella3_2.connect(self.signalIzabella3_2exec)
        self.worker3.signalIzabella4_1.connect(self.signalIzabella4_1exec)
        self.worker3.signalIzabella4_2.connect(self.signalIzabella4_2exec)
        self.worker4.signalJoao1_1.connect(self.signalJoao1_1exec)
        self.worker4.signalJoao1_2.connect(self.signalJoao1_2exec)
        self.worker4.signalJoao2_1.connect(self.signalJoao2_1exec)
        self.worker4.signalJoao2_2.connect(self.signalJoao2_2exec)
        self.worker4.signalJoao3_1.connect(self.signalJoao3_1exec)
        self.worker4.signalJoao3_2.connect(self.signalJoao3_2exec)
        self.worker4.signalJoao4_1.connect(self.signalJoao4_1exec)
        self.worker4.signalJoao4_2.connect(self.signalJoao4_2exec)
        self.worker5.signalManuela1_1.connect(self.signalManuela1_1exec)
        self.worker5.signalManuela1_2.connect(self.signalManuela1_2exec)
        self.worker5.signalManuela2_1.connect(self.signalManuela2_1exec)
        self.worker5.signalManuela2_2.connect(self.signalManuela2_2exec)
        self.worker5.signalManuela3_1.connect(self.signalManuela3_1exec)
        self.worker5.signalManuela3_2.connect(self.signalManuela3_2exec)
        self.worker5.signalManuela4_1.connect(self.signalManuela4_1exec)
        self.worker5.signalManuela4_2.connect(self.signalManuela4_2exec)
        self.worker6.signalMaria1_1.connect(self.signalMaria1_1exec)
        self.worker6.signalMaria1_2.connect(self.signalMaria1_2exec)
        self.worker6.signalMaria2_1.connect(self.signalMaria2_1exec)
        self.worker6.signalMaria2_2.connect(self.signalMaria2_2exec)
        self.worker6.signalMaria3_1.connect(self.signalMaria3_1exec)
        self.worker6.signalMaria3_2.connect(self.signalMaria3_2exec)
        self.worker6.signalMaria4_1.connect(self.signalMaria4_1exec)
        self.worker6.signalMaria4_2.connect(self.signalMaria4_2exec)
        self.worker7.signalGabriel1_1.connect(self.signalGabriel1_1exec)
        self.worker7.signalGabriel1_2.connect(self.signalGabriel1_2exec)
        self.worker7.signalGabriel2_1.connect(self.signalGabriel2_1exec)
        self.worker7.signalGabriel2_2.connect(self.signalGabriel2_2exec)
        self.worker7.signalGabriel3_1.connect(self.signalGabriel3_1exec)
        self.worker7.signalGabriel3_2.connect(self.signalGabriel3_2exec)
        self.worker7.signalGabriel4_1.connect(self.signalGabriel4_1exec)
        self.worker7.signalGabriel4_2.connect(self.signalGabriel4_2exec)
        self.worker8.signalFelipe1_1.connect(self.signalFelipe1_1exec)
        self.worker8.signalFelipe1_2.connect(self.signalFelipe1_2exec)
        self.worker8.signalFelipe2_1.connect(self.signalFelipe2_1exec)
        self.worker8.signalFelipe2_2.connect(self.signalFelipe2_2exec)
        self.worker8.signalFelipe3_1.connect(self.signalFelipe3_1exec)
        self.worker8.signalFelipe3_2.connect(self.signalFelipe3_2exec)
        self.worker8.signalFelipe4_1.connect(self.signalFelipe4_1exec)
        self.worker8.signalFelipe4_2.connect(self.signalFelipe4_2exec)
        self.worker9.signalLarinha1_1.connect(self.signalLarinha1_1exec)
        self.worker9.signalLarinha1_2.connect(self.signalLarinha1_2exec)
        self.worker9.signalLarinha2_1.connect(self.signalLarinha2_1exec)
        self.worker9.signalLarinha2_2.connect(self.signalLarinha2_2exec)
        self.worker9.signalLarinha3_1.connect(self.signalLarinha3_1exec)
        self.worker9.signalLarinha3_2.connect(self.signalLarinha3_2exec)
        self.worker9.signalLarinha4_1.connect(self.signalLarinha4_1exec)
        self.worker9.signalLarinha4_2.connect(self.signalLarinha4_2exec)
        self.worker10.signalBruno1_1.connect(self.signalBruno1_1exec)
        self.worker10.signalBruno1_2.connect(self.signalBruno1_2exec)
        self.worker10.signalBruno2_1.connect(self.signalBruno2_1exec)
        self.worker10.signalBruno2_2.connect(self.signalBruno2_2exec)
        self.worker10.signalBruno3_1.connect(self.signalBruno3_1exec)
        self.worker10.signalBruno3_2.connect(self.signalBruno3_2exec)
        self.worker10.signalBruno4_1.connect(self.signalBruno4_1exec)
        self.worker10.signalBruno4_2.connect(self.signalBruno4_2exec)
        self.worker11.signalJulia1_1.connect(self.signalJulia1_1exec)
        self.worker11.signalJulia1_2.connect(self.signalJulia1_2exec)
        self.worker11.signalJulia2_1.connect(self.signalJulia2_1exec)
        self.worker11.signalJulia2_2.connect(self.signalJulia2_2exec)
        self.worker11.signalJulia3_1.connect(self.signalJulia3_1exec)
        self.worker11.signalJulia3_2.connect(self.signalJulia3_2exec)
        self.worker11.signalJulia4_1.connect(self.signalJulia4_1exec)
        self.worker11.signalJulia4_2.connect(self.signalJulia4_2exec)
        self.workerLabel.signalLabel1_1.connect(self.signalLabel1)
        self.workerLabel.signalLabel2_1.connect(self.signalLabel2)
        self.workerLabel.signalLabel3_1.connect(self.signalLabel3)
        self.workerLabel.signalLabel4_1.connect(self.signalLabel4)

    # Click the Stop button
    def stopPressed(self):

        # Reset all the changes, every bathroom is empty again and every resident is back at home
        self.labelRunningT.hide()
        global bathBigVF
        global bathSmallVF
        global bathTopVF
        bathBigVF = "f"
        bathSmallVF = "f"
        bathTopVF = "f"


        self.worker.bathVF = "f"
        self.worker.bathBigVFmath = "f"
        self.worker.bathSmallVFmath = "f"
        self.worker.bathTopVFmath = "f"

        self.worker2.bathVF = "f"
        self.worker2.bathBigVFluan = "f"
        self.worker2.bathSmallVFluan = "f"
        self.worker2.bathTopVFluan = "f"

        self.worker3.bathVF = "f"
        self.worker3.bathBigVFiza = "f"
        self.worker3.bathSmallVFiza = "f"
        self.worker3.bathTopVFiza = "f"

        self.worker4.bathVF = "f"
        self.worker4.bathBigVFjoao = "f"
        self.worker4.bathSmallVFjoao = "f"
        self.worker4.bathTopVFjoao = "f"

        self.worker5.bathVF = "f"
        self.worker5.bathBigVFmanu = "f"
        self.worker5.bathSmallVFmanu = "f"
        self.worker5.bathTopVFmanu = "f"

        self.worker6.bathVF = "f"
        self.worker6.bathBigVFmr = "f"
        self.worker6.bathSmallVFmr = "f"
        self.worker6.bathTopVFmr = "f"

        self.worker7.bathVF = "f"
        self.worker7.bathBigVFgabi = "f"
        self.worker7.bathSmallVFgabi = "f"
        self.worker7.bathTopVFgabi = "f"

        self.worker8.bathVF = "f"
        self.worker8.bathBigVFfelp = "f"
        self.worker8.bathSmallVFfelp = "f"
        self.worker8.bathTopVFfelp = "f"

        self.worker9.bathVF = "f"
        self.worker9.bathBigVFlr = "f"
        self.worker9.bathSmallVFlr = "f"
        self.worker9.bathTopVFlr = "f"

        self.worker10.bathVF = "f"
        self.worker10.bathBigVFbr = "f"
        self.worker10.bathSmallVFbr = "f"
        self.worker10.bathTopVFbr = "f"

        self.worker11.bathVF = "f"
        self.worker11.bathBigVFjul = "f"
        self.worker11.bathSmallVFjul = "f"
        self.worker11.bathTopVFjul = "f"

        self.T_bathBig.setText("Free")
        self.T_bathSmall.setText("Free")
        self.T_bathTop.setText("Free")
        self.T_bathBig.setStyleSheet("background-color: lime")
        self.T_bathSmall.setStyleSheet("background-color: lime")
        self.T_bathTop.setStyleSheet("background-color: lime")
        self.T_matheus_home.setText("at Home")
        self.T_matheus_home.setStyleSheet("background-color: lime")
        self.T_luan_home.setText("at Home")
        self.T_luan_home.setStyleSheet("background-color: lime")
        self.T_joao_home.setText("at Home")
        self.T_joao_home.setStyleSheet("background-color: lime")
        self.T_manuela_home.setText("at Home")
        self.T_manuela_home.setStyleSheet("background-color: lime")
        self.T_larinha_home.setText("at Home")
        self.T_larinha_home.setStyleSheet("background-color: lime")
        self.T_bruno_home.setText("at Home")
        self.T_bruno_home.setStyleSheet("background-color: lime")
        self.T_maria_home.setText("at Home")
        self.T_maria_home.setStyleSheet("background-color: lime")
        self.T_felipe_home.setText("at Home")
        self.T_felipe_home.setStyleSheet("background-color: lime")
        self.T_iza_home.setText("at Home")
        self.T_iza_home.setStyleSheet("background-color: lime")
        self.T_julia_home.setText("at Home")
        self.T_julia_home.setStyleSheet("background-color: lime")
        self.T_gabriel_home.setText("at Home")
        self.T_gabriel_home.setStyleSheet("background-color: lime")

        # The Counter of residents at home also gets resetted to 11
        global Casa_Count
        Casa_Count = 11
        self.T_homeCounter.setText(f"at Home : {Casa_Count}")

        # All the Threads are terminated and quitted
        self.worker.terminate()
        self.worker2.terminate()
        self.worker3.terminate()
        self.worker4.terminate()
        self.worker5.terminate()
        self.worker6.terminate()
        self.worker7.terminate()
        self.worker8.terminate()
        self.worker9.terminate()
        self.worker10.terminate()
        self.worker11.terminate()
        self.workerLabel.terminate()

        self.worker.quit()
        self.worker2.quit()
        self.worker3.quit()
        self.worker4.quit()
        self.worker5.quit()
        self.worker6.quit()
        self.worker7.quit()
        self.worker8.quit()
        self.worker9.quit()
        self.worker10.quit()
        self.worker11.quit()
        self.workerLabel.quit()

        self.labelRunningT.hide()




    # The signals, every signal leads to a certain change of text and color of certain labels
    def signalMatheus1_1exec(self):
        global Casa_Count
        if self.T_matheus_home.text() == "at Home":
            Casa_Count -= 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_matheus_home.setText("Outside")
        self.T_matheus_home.setStyleSheet("background-color: red")

    def signalMatheus1_2exec(self):
        global Casa_Count
        if self.T_matheus_home.text() == "Outside":
            Casa_Count += 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_matheus_home.setText("at Home")
        self.T_matheus_home.setStyleSheet("background-color: lime")

    def signalMatheus2_1exec(self):
        self.T_bathBig.setText("Free")
        self.T_bathBig.setStyleSheet("background-color: lime")

    def signalMatheus2_2exec(self):
        self.T_bathBig.setText("Occupied")
        self.T_bathBig.setStyleSheet("background-color: red")

    def signalMatheus3_1exec(self):
        self.T_bathSmall.setText("Free")
        self.T_bathSmall.setStyleSheet("background-color: lime")

    def signalMatheus3_2exec(self):
        self.T_bathSmall.setText("Occupied")
        self.T_bathSmall.setStyleSheet("background-color: red")

    def signalMatheus4_1exec(self):
        self.T_bathTop.setText("Free")
        self.T_bathTop.setStyleSheet("background-color: lime")

    def signalMatheus4_2exec(self):
        self.T_bathTop.setText("Occupied")
        self.T_bathTop.setStyleSheet("background-color: red")

    def signalLuan1_1exec(self):
        global Casa_Count
        if self.T_luan_home.text() == "at Home":
            Casa_Count -= 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_luan_home.setText("Outside")
        self.T_luan_home.setStyleSheet("background-color: red")

    def signalLuan1_2exec(self):
        global Casa_Count
        if self.T_luan_home.text() == "Outside":
            Casa_Count += 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_luan_home.setText("at Home")
        self.T_luan_home.setStyleSheet("background-color: lime")

    def signalLuan2_1exec(self):
        self.T_bathBig.setText("Free")
        self.T_bathBig.setStyleSheet("background-color: lime")

    def signalLuan2_2exec(self):
        self.T_bathBig.setText("Occupied")
        self.T_bathBig.setStyleSheet("background-color: red")

    def signalLuan3_1exec(self):
        self.T_bathSmall.setText("Free")
        self.T_bathSmall.setStyleSheet("background-color: lime")

    def signalLuan3_2exec(self):
        self.T_bathSmall.setText("Occupied")
        self.T_bathSmall.setStyleSheet("background-color: red")

    def signalLuan4_1exec(self):
        self.T_bathTop.setText("Free")
        self.T_bathTop.setStyleSheet("background-color: lime")

    def signalLuan4_2exec(self):
        self.T_bathTop.setText("Occupied")
        self.T_bathTop.setStyleSheet("background-color: red")

    def signalIzabella1_1exec(self):
        global Casa_Count
        if self.T_iza_home.text() == "at Home":
            Casa_Count -= 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_iza_home.setText("Outside")
        self.T_iza_home.setStyleSheet("background-color: red")

    def signalIzabella1_2exec(self):
        global Casa_Count
        if self.T_iza_home.text() == "Outside":
            Casa_Count += 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_iza_home.setText("at Home")
        self.T_iza_home.setStyleSheet("background-color: lime")

    def signalIzabella2_1exec(self):
        self.T_bathBig.setText("Free")
        self.T_bathBig.setStyleSheet("background-color: lime")

    def signalIzabella2_2exec(self):
        self.T_bathBig.setText("Occupied")
        self.T_bathBig.setStyleSheet("background-color: red")

    def signalIzabella3_1exec(self):
        self.T_bathSmall.setText("Free")
        self.T_bathSmall.setStyleSheet("background-color: lime")

    def signalIzabella3_2exec(self):
        self.T_bathSmall.setText("Occupied")
        self.T_bathSmall.setStyleSheet("background-color: red")

    def signalIzabella4_1exec(self):
        self.T_bathTop.setText("Free")
        self.T_bathTop.setStyleSheet("background-color: lime")

    def signalIzabella4_2exec(self):
        self.T_bathTop.setText("Occupied")
        self.T_bathTop.setStyleSheet("background-color: red")

    def signalJoao1_1exec(self):
        global Casa_Count
        if self.T_joao_home.text() == "at Home":
            Casa_Count -= 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_joao_home.setText("Outside")
        self.T_joao_home.setStyleSheet("background-color: red")

    def signalJoao1_2exec(self):
        global Casa_Count
        if self.T_joao_home.text() == "Outside":
            Casa_Count += 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_joao_home.setText("at Home")
        self.T_joao_home.setStyleSheet("background-color: lime")

    def signalJoao2_1exec(self):
        self.T_bathBig.setText("Free")
        self.T_bathBig.setStyleSheet("background-color: lime")

    def signalJoao2_2exec(self):
        self.T_bathBig.setText("Occupied")
        self.T_bathBig.setStyleSheet("background-color: red")

    def signalJoao3_1exec(self):
        self.T_bathSmall.setText("Free")
        self.T_bathSmall.setStyleSheet("background-color: lime")

    def signalJoao3_2exec(self):
        self.T_bathSmall.setText("Occupied")
        self.T_bathSmall.setStyleSheet("background-color: red")

    def signalJoao4_1exec(self):
        self.T_bathTop.setText("Free")
        self.T_bathTop.setStyleSheet("background-color: lime")

    def signalJoao4_2exec(self):
        self.T_bathTop.setText("Occupied")
        self.T_bathTop.setStyleSheet("background-color: red")

    def signalManuela1_1exec(self):
        global Casa_Count
        if self.T_manuela_home.text() == "at Home":
            Casa_Count -= 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_manuela_home.setText("Outside")
        self.T_manuela_home.setStyleSheet("background-color: red")

    def signalManuela1_2exec(self):
        global Casa_Count
        if self.T_manuela_home.text() == "Outside":
            Casa_Count += 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_manuela_home.setText("at Home")
        self.T_manuela_home.setStyleSheet("background-color: lime")

    def signalManuela2_1exec(self):
        self.T_bathBig.setText("Free")
        self.T_bathBig.setStyleSheet("background-color: lime")

    def signalManuela2_2exec(self):
        self.T_bathBig.setText("Occupied")
        self.T_bathBig.setStyleSheet("background-color: red")

    def signalManuela3_1exec(self):
        self.T_bathSmall.setText("Free")
        self.T_bathSmall.setStyleSheet("background-color: lime")

    def signalManuela3_2exec(self):
        self.T_bathSmall.setText("Occupied")
        self.T_bathSmall.setStyleSheet("background-color: red")

    def signalManuela4_1exec(self):
        self.T_bathTop.setText("Free")
        self.T_bathTop.setStyleSheet("background-color: lime")

    def signalManuela4_2exec(self):
        self.T_bathTop.setText("Occupied")
        self.T_bathTop.setStyleSheet("background-color: red")

    def signalMaria1_1exec(self):
        global Casa_Count
        if self.T_maria_home.text() == "at Home":
            Casa_Count -= 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_maria_home.setText("Outside")
        self.T_maria_home.setStyleSheet("background-color: red")

    def signalMaria1_2exec(self):
        global Casa_Count
        if self.T_maria_home.text() == "Outside":
            Casa_Count += 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_maria_home.setText("at Home")
        self.T_maria_home.setStyleSheet("background-color: lime")

    def signalMaria2_1exec(self):
        self.T_bathBig.setText("Free")
        self.T_bathBig.setStyleSheet("background-color: lime")

    def signalMaria2_2exec(self):
        self.T_bathBig.setText("Occupied")
        self.T_bathBig.setStyleSheet("background-color: red")

    def signalMaria3_1exec(self):
        self.T_bathSmall.setText("Free")
        self.T_bathSmall.setStyleSheet("background-color: lime")

    def signalMaria3_2exec(self):
        self.T_bathSmall.setText("Occupied")
        self.T_bathSmall.setStyleSheet("background-color: red")

    def signalMaria4_1exec(self):
        self.T_bathTop.setText("Free")
        self.T_bathTop.setStyleSheet("background-color: lime")

    def signalMaria4_2exec(self):
        self.T_bathTop.setText("Occupied")
        self.T_bathTop.setStyleSheet("background-color: red")

    def signalGabriel1_1exec(self):
        global Casa_Count
        if self.T_gabriel_home.text() == "at Home":
            Casa_Count -= 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_gabriel_home.setText("Outside")
        self.T_gabriel_home.setStyleSheet("background-color: red")

    def signalGabriel1_2exec(self):
        global Casa_Count
        if self.T_gabriel_home.text() == "Outside":
            Casa_Count += 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_gabriel_home.setText("at Home")
        self.T_gabriel_home.setStyleSheet("background-color: lime")

    def signalGabriel2_1exec(self):
        self.T_bathBig.setText("Free")
        self.T_bathBig.setStyleSheet("background-color: lime")

    def signalGabriel2_2exec(self):
        self.T_bathBig.setText("Occupied")
        self.T_bathBig.setStyleSheet("background-color: red")

    def signalGabriel3_1exec(self):
        self.T_bathSmall.setText("Free")
        self.T_bathSmall.setStyleSheet("background-color: lime")

    def signalGabriel3_2exec(self):
        self.T_bathSmall.setText("Occupied")
        self.T_bathSmall.setStyleSheet("background-color: red")

    def signalGabriel4_1exec(self):
        self.T_bathTop.setText("Free")
        self.T_bathTop.setStyleSheet("background-color: lime")

    def signalGabriel4_2exec(self):
        self.T_bathTop.setText("Occupied")
        self.T_bathTop.setStyleSheet("background-color: red")

    def signalFelipe1_1exec(self):
        global Casa_Count
        if self.T_felipe_home.text() == "at Home":
            Casa_Count -= 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_felipe_home.setText("Outside")
        self.T_felipe_home.setStyleSheet("background-color: red")

    def signalFelipe1_2exec(self):
        global Casa_Count
        if self.T_felipe_home.text() == "Outside":
            Casa_Count += 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_felipe_home.setText("at Home")
        self.T_felipe_home.setStyleSheet("background-color: lime")

    def signalFelipe2_1exec(self):
        self.T_bathBig.setText("Free")
        self.T_bathBig.setStyleSheet("background-color: lime")

    def signalFelipe2_2exec(self):
        self.T_bathBig.setText("Occupied")
        self.T_bathBig.setStyleSheet("background-color: red")

    def signalFelipe3_1exec(self):
        self.T_bathSmall.setText("Free")
        self.T_bathSmall.setStyleSheet("background-color: lime")

    def signalFelipe3_2exec(self):
        self.T_bathSmall.setText("Occupied")
        self.T_bathSmall.setStyleSheet("background-color: red")

    def signalFelipe4_1exec(self):
        self.T_bathTop.setText("Free")
        self.T_bathTop.setStyleSheet("background-color: lime")

    def signalFelipe4_2exec(self):
        self.T_bathTop.setText("Occupied")
        self.T_bathTop.setStyleSheet("background-color: red")

    def signalLarinha1_1exec(self):
        global Casa_Count
        if self.T_larinha_home.text() == "at Home":
            Casa_Count -= 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_larinha_home.setText("Outside")
        self.T_larinha_home.setStyleSheet("background-color: red")

    def signalLarinha1_2exec(self):
        global Casa_Count
        if self.T_larinha_home.text() == "Outside":
            Casa_Count += 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_larinha_home.setText("at Home")
        self.T_larinha_home.setStyleSheet("background-color: lime")

    def signalLarinha2_1exec(self):
        self.T_bathBig.setText("Free")
        self.T_bathBig.setStyleSheet("background-color: lime")

    def signalLarinha2_2exec(self):
        self.T_bathBig.setText("Occupied")
        self.T_bathBig.setStyleSheet("background-color: red")

    def signalLarinha3_1exec(self):
        self.T_bathSmall.setText("Free")
        self.T_bathSmall.setStyleSheet("background-color: lime")

    def signalLarinha3_2exec(self):
        self.T_bathSmall.setText("Occupied")
        self.T_bathSmall.setStyleSheet("background-color: red")

    def signalLarinha4_1exec(self):
        self.T_bathTop.setText("Free")
        self.T_bathTop.setStyleSheet("background-color: lime")

    def signalLarinha4_2exec(self):
        self.T_bathTop.setText("Occupied")
        self.T_bathTop.setStyleSheet("background-color: red")

    def signalBruno1_1exec(self):
        global Casa_Count
        if self.T_bruno_home.text() == "at Home":
            Casa_Count -= 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_bruno_home.setText("Outside")
        self.T_bruno_home.setStyleSheet("background-color: red")

    def signalBruno1_2exec(self):
        global Casa_Count
        if self.T_bruno_home.text() == "Outside":
            Casa_Count += 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_bruno_home.setText("at Home")
        self.T_bruno_home.setStyleSheet("background-color: lime")

    def signalBruno2_1exec(self):
        self.T_bathBig.setText("Free")
        self.T_bathBig.setStyleSheet("background-color: lime")

    def signalBruno2_2exec(self):
        self.T_bathBig.setText("Occupied")
        self.T_bathBig.setStyleSheet("background-color: red")

    def signalBruno3_1exec(self):
        self.T_bathSmall.setText("Free")
        self.T_bathSmall.setStyleSheet("background-color: lime")

    def signalBruno3_2exec(self):
        self.T_bathSmall.setText("Occupied")
        self.T_bathSmall.setStyleSheet("background-color: red")

    def signalBruno4_1exec(self):
        self.T_bathTop.setText("Free")
        self.T_bathTop.setStyleSheet("background-color: lime")

    def signalBruno4_2exec(self):
        self.T_bathTop.setText("Occupied")
        self.T_bathTop.setStyleSheet("background-color: red")

    def signalJulia1_1exec(self):
        global Casa_Count
        if self.T_julia_home.text() == "at Home":
            Casa_Count -= 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_julia_home.setText("Outside")
        self.T_julia_home.setStyleSheet("background-color: red")

    def signalJulia1_2exec(self):
        global Casa_Count
        if self.T_julia_home.text() == "Outside":
            Casa_Count += 1
            self.T_homeCounter.setText(f"at Home : {Casa_Count}")
        self.T_julia_home.setText("at Home")
        self.T_julia_home.setStyleSheet("background-color: lime")

    def signalJulia2_1exec(self):
        self.T_bathBig.setText("Free")
        self.T_bathBig.setStyleSheet("background-color: lime")

    def signalJulia2_2exec(self):
        self.T_bathBig.setText("Occupied")
        self.T_bathBig.setStyleSheet("background-color: red")

    def signalJulia3_1exec(self):
        self.T_bathSmall.setText("Free")
        self.T_bathSmall.setStyleSheet("background-color: lime")

    def signalJulia3_2exec(self):
        self.T_bathSmall.setText("Occupied")
        self.T_bathSmall.setStyleSheet("background-color: red")

    def signalJulia4_1exec(self):
        self.T_bathTop.setText("Free")
        self.T_bathTop.setStyleSheet("background-color: lime")

    def signalJulia4_2exec(self):
        self.T_bathTop.setText("Occupied")
        self.T_bathTop.setStyleSheet("background-color: red")

    def signalLabel1(self):
        self.labelRunningT.setText("Running.")

    def signalLabel2(self):
        self.labelRunningT.setText("Running..")

    def signalLabel3(self):
        self.labelRunningT.setText("Running...")

    def signalLabel4(self):
        self.labelRunningT.show()

    def setupUi(self, Total):
        Total.setObjectName("Total")
        Total.resize(932, 752)

        # Background Image
        self.photo1 = QtWidgets.QLabel(Total)
        self.photo1.setGeometry(QtCore.QRect(0, 0, 932, 752))
        self.photo1.setText("")                
        self.photo1.setPixmap(QtGui.QPixmap("./pics/Fundo.png"))
        self.photo1.setScaledContents(True)
        self.photo1.setObjectName("photo1")

        self.T_textBrowser = QtWidgets.QTextBrowser(Total)
        self.T_textBrowser.setGeometry(QtCore.QRect(100, 70, 111, 541))
        self.T_textBrowser.setObjectName("T_textBrowser")
        self.T_larinha_home = QtWidgets.QLabel(Total)
        self.T_larinha_home.setGeometry(QtCore.QRect(260, 170, 91, 41))
        self.T_larinha_home.setObjectName("T_larinha_home")
        self.T_iza_home = QtWidgets.QLabel(Total)
        self.T_iza_home.setGeometry(QtCore.QRect(260, 400, 91, 41))
        self.T_iza_home.setObjectName("T_iza_home")
        self.T_matheus_home = QtWidgets.QLabel(Total)
        self.T_matheus_home.setGeometry(QtCore.QRect(260, 500, 91, 41))
        self.T_matheus_home.setObjectName("T_matheus_home")
        self.T_maria_home = QtWidgets.QLabel(Total)
        self.T_maria_home.setGeometry(QtCore.QRect(260, 450, 91, 41))
        self.T_maria_home.setObjectName("T_maria_home")
        self.T_julia_home = QtWidgets.QLabel(Total)
        self.T_julia_home.setGeometry(QtCore.QRect(260, 70, 91, 41))
        self.T_julia_home.setObjectName("T_julia_home")
        self.T_luan_home = QtWidgets.QLabel(Total)
        self.T_luan_home.setGeometry(QtCore.QRect(260, 350, 91, 41))
        self.T_luan_home.setObjectName("T_luan_home")
        self.label = QtWidgets.QLabel(Total)
        self.label.setGeometry(QtCore.QRect(240, 20, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.T_bruno_home = QtWidgets.QLabel(Total)
        self.T_bruno_home.setGeometry(QtCore.QRect(260, 120, 91, 41))
        self.T_bruno_home.setObjectName("T_bruno_home")
        self.T_homeCounter = QtWidgets.QLabel(Total)
        self.T_homeCounter.setGeometry(QtCore.QRect(450, 50, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.T_homeCounter.setFont(font)
        self.T_homeCounter.setObjectName("T_homeCounter")
        self.T_joao_home = QtWidgets.QLabel(Total)
        self.T_joao_home.setGeometry(QtCore.QRect(260, 310, 91, 41))
        self.T_joao_home.setObjectName("T_joao_home")
        self.T_manuela_home = QtWidgets.QLabel(Total)
        self.T_manuela_home.setGeometry(QtCore.QRect(260, 550, 91, 41))
        self.T_manuela_home.setObjectName("T_manuela_home")
        self.T_gabriel_home = QtWidgets.QLabel(Total)
        self.T_gabriel_home.setGeometry(QtCore.QRect(260, 260, 91, 41))
        self.T_gabriel_home.setObjectName("T_gabriel_home")
        self.T_felipe_home = QtWidgets.QLabel(Total)
        self.T_felipe_home.setGeometry(QtCore.QRect(260, 210, 91, 41))
        self.T_felipe_home.setObjectName("T_felipe_home")
        self.textBrowser = QtWidgets.QTextBrowser(Total)
        self.textBrowser.setGeometry(QtCore.QRect(400, 200, 251, 301))
        self.textBrowser.setObjectName("textBrowser")
        self.T_bathBig = QtWidgets.QLabel(Total)
        self.T_bathBig.setGeometry(QtCore.QRect(740, 210, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.T_bathBig.setFont(font)
        self.T_bathBig.setObjectName("T_bathBig")
        self.T_bathSmall = QtWidgets.QLabel(Total)
        self.T_bathSmall.setGeometry(QtCore.QRect(740, 300, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.T_bathSmall.setFont(font)
        self.T_bathSmall.setObjectName("T_bathSmall")
        self.T_bathTop = QtWidgets.QLabel(Total)
        self.T_bathTop.setGeometry(QtCore.QRect(740, 410, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.T_bathTop.setFont(font)
        self.T_bathTop.setObjectName("T_bathTop")

        # Start Button
        self.buttonTotalStart = QtWidgets.QPushButton(Total,
                                                       clicked=lambda: self.clickedStartBtn())
        self.buttonTotalStart.setText("Start")
        self.buttonTotalStart.setFont(QFont('Arial', 15))
        self.buttonTotalStart.setGeometry(500, 600, 150, 50)
        self.buttonTotalStart.setStyleSheet("QPushButton"
                                             "{"
                                             "background-color : black;"
                                             "color : white;"
                                             "border :7px solid ;"
                                             "border-top-color : lime; "
                                             "border-left-color :lime;"
                                             "border-right-color :lime;"
                                             "border-bottom-color : lime"
                                             "}"
                                             "QPushButton::pressed"
                                             "{"
                                             "border :7px solid ;"
                                             "border-top-color : black; "
                                             "border-left-color :black;"
                                             "border-right-color :black;"
                                             "border-bottom-color : black"
                                             "}"
                                             )

        # Stop Button
        self.buttonTotalStop = QtWidgets.QPushButton(Total, clicked=lambda: self.stopPressed())
        self.buttonTotalStop.setText("Stop")
        self.buttonTotalStop.setFont(QFont('Arial', 15))
        self.buttonTotalStop.setGeometry(500, 670, 150, 50)
        self.buttonTotalStop.setStyleSheet("QPushButton"
                                           "{"
                                           "background-color : black;"
                                           "color : white;"
                                           "border :7px solid ;"
                                           "border-top-color : red; "
                                           "border-left-color :red;"
                                           "border-right-color :red;"
                                           "border-bottom-color : red"
                                           "}"
                                           "QPushButton::pressed"
                                           "{"
                                           "border :7px solid ;"
                                           "border-top-color : black; "
                                           "border-left-color :black;"
                                           "border-right-color :black;"
                                           "border-bottom-color : black"
                                           "}")

        self.labelRunningT = QLabel(Total)
        self.labelRunningT.setText("Running...")
        self.labelRunningT.setGeometry(200, 630, 200, 100)
        self.labelRunningT.setFont(QFont('Arial', 15))
        self.labelRunningT.hide()

        self.retranslateUi(Total)
        QtCore.QMetaObject.connectSlotsByName(Total)

    def retranslateUi(self, Total):
        _translate = QtCore.QCoreApplication.translate
        Total.setWindowTitle(_translate("Total", "Total"))
        self.T_textBrowser.setHtml(_translate("Total",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Julia:</span></p>\n"
                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Bruno:</span></p>\n"
                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Larinha:</span></p>\n"
                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Felipe:</span></p>\n"
                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Gabriel:</span></p>\n"
                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Joao:</span></p>\n"
                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Luan:</span></p>\n"
                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Izabella:</span></p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\"><br />Maria:</span></p>\n"
                                              "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Matheus:</span></p>\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\"><br />Manuela:</span></p></body></html>"))
        self.T_larinha_home.setText(_translate("Total", "at Home"))
        self.T_iza_home.setText(_translate("Total", "at Home"))
        self.T_matheus_home.setText(_translate("Total", "at Home"))
        self.T_maria_home.setText(_translate("Total", "at Home"))
        self.T_julia_home.setText(_translate("Total", "at Home"))
        self.T_luan_home.setText(_translate("Total", "at Home"))
        # self.label.setText(_translate("Total", ""))
        self.T_bruno_home.setText(_translate("Total", "at Home"))
        self.T_homeCounter.setText(_translate("Total", "at Home : 11"))
        self.T_joao_home.setText(_translate("Total", "at Home"))
        self.T_manuela_home.setText(_translate("Total", "at Home"))
        self.T_gabriel_home.setText(_translate("Total", "at Home"))
        self.T_felipe_home.setText(_translate("Total", "at Home"))
        self.T_julia_home.setStyleSheet("background-color: lime")
        self.T_luan_home.setStyleSheet("background-color: lime")
        self.T_maria_home.setStyleSheet("background-color: lime")
        self.T_joao_home.setStyleSheet("background-color: lime")
        self.T_iza_home.setStyleSheet("background-color: lime")
        self.T_larinha_home.setStyleSheet("background-color: lime")
        self.T_bruno_home.setStyleSheet("background-color: lime")
        self.T_gabriel_home.setStyleSheet("background-color: lime")
        self.T_matheus_home.setStyleSheet("background-color: lime")
        self.T_felipe_home.setStyleSheet("background-color: lime")
        self.T_manuela_home.setStyleSheet("background-color: lime")
        self.textBrowser.setHtml(_translate("Total",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Big Bathroom:</span></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p>\n"
                                            "<p style=\" margin-top:30px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Small Bathroom:</span></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p>\n"
                                            "<p style=\" margin-top:30px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Top Bathroom:</span></p></body></html>"))
        self.T_bathBig.setText(_translate("Total", "Free"))
        self.T_bathSmall.setText(_translate("Total", "Free"))
        self.T_bathTop.setText(_translate("Total", "Free"))
        self.T_bathBig.setStyleSheet("background-color: lime")
        self.T_bathSmall.setStyleSheet("background-color: lime")
        self.T_bathTop.setStyleSheet("background-color: lime")


# Run Method, if you just want to run this window and not the whole program
if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Total = QtWidgets.QWidget()
    ui = Ui_Total()
    ui.setupUi(Total)
    Total.show()
    sys.exit(app.exec_())
